# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c2d7c83b7c805c03e0ef60f94e584dc965f135d5e843aeb57686240fe4b4f994f0bd588e13ce96f33561a5325fe478f2821f0866f845e3da20b7f3d9ab4198d7

test:
  secret_key_base: 865a0cef7cd45cb3d941187901393e7a95402579dfd355a65106c08f00d4314b7a47efb0954028bd7968b84ee69f7c36bec671556b3c714e27ce5ec8e1ac1870

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
